### ISSUE TITLE
Getting error after installation

### ISSUE THREAD

**Issue by finity69x2** [custom-cards/gauge-card#1]
I just installed the card thru HACS.

I configured the card as:

```
  - type: custom:gauge-card
    title: Temperature
    entity: sensor.livingroom_temperature
    min: 0
    max: 100
    severity:
      red: 40
      green: 65
      amber: 80
```

After refreshing lovelace I get the following error:

"Failed to execute 'attachShadow' on 'Element. Shadow root cannot be created on a host which already hosts a shadow tree"

I saw on the forum thread for the card that the fix was to comment out line 24 of the .js file.

I did that and it's now working but I'm not sure that is a proper fix. It's happened to several people in that thread.

Is there a plan to address this so we don't need to customize our own custom cards?
