### ISSUE TITLE
The gauge overflows when the card is not wide enough

### ISSUE THREAD

**Issue by igorsantos07** [custom-cards/gauge-card#18]
This could happen on grids, horizontal stacks, or even in the newer Sections dashboard type.

![image](https://github.com/user-attachments/assets/118d1d60-cf87-4f4c-bdd9-145bdc923b7f)

Example:
```yaml
type: horizontal-stack
cards:
  - type: custom:gauge-card
    entity: xyz
  - type: gauge
    entity: xyz
```
